var searchData=
[
  ['a_20csv_0',['Loading Parameter Combinations From a CSV',['../index.html#autotoc_md8',1,'']]],
  ['acknowledgements_1',['Acknowledgements',['../index.html#autotoc_md17',1,'']]],
  ['adding_20parameters_20and_20alternative_20likelihood_20calculators_2',['Adding Parameters and Alternative Likelihood Calculators',['../index.html#autotoc_md12',1,'']]],
  ['addm_3',['aDDM',['../classaDDM.html',1,'aDDM'],['../classaDDM.html#a11abdbfa9c9d9edb1c796d1c440fc241',1,'aDDM::aDDM(float d, float sigma, float theta, float k=0, float barrier=1, unsigned int nonDecisionTime=0, float bias=0, float decay=0)'],['../classaDDM.html#a3deca5544adba4e2ad8ec86a0efdbcfc',1,'aDDM::aDDM()']]],
  ['addm_20cpp_4',['ADDM.cpp',['../index.html',1,'']]],
  ['addm_2ecpp_5',['addm.cpp',['../addm_8cpp.html',1,'']]],
  ['addm_2eh_6',['addm.h',['../addm_8h.html',1,'']]],
  ['addm_5fcsv_5ffit_2ecpp_7',['addm_csv_fit.cpp',['../addm__csv__fit_8cpp.html',1,'']]],
  ['addm_5fmle_2ecpp_8',['addm_mle.cpp',['../addm__mle_8cpp.html',1,'']]],
  ['addm_5fmle_2epy_9',['addm_mle.py',['../addm__mle_8py.html',1,'']]],
  ['addm_5fsimulate_2ecpp_10',['addm_simulate.cpp',['../addm__simulate_8cpp.html',1,'']]],
  ['addm_5ftest_2ecpp_11',['addm_test.cpp',['../addm__test_8cpp.html',1,'']]],
  ['addmtrial_12',['aDDMTrial',['../classaDDMTrial.html',1,'aDDMTrial'],['../classaDDMTrial.html#aa10527b5851a8395529eff1e8ad86adc',1,'aDDMTrial::aDDMTrial(unsigned int RT, int choice, int valueLeft, int valueRight, vector&lt; int &gt; fixItem={}, vector&lt; int &gt; fixTime={}, vector&lt; float &gt; fixRDV={}, float uninterruptedLastFixTime=0)'],['../classaDDMTrial.html#ae406a1f1ae278a292421caedafda67a2',1,'aDDMTrial::aDDMTrial()']]],
  ['addparameter_13',['addParameter',['../classaDDM.html#a720af5433bd6f987f487d96766222eaf',1,'aDDM']]],
  ['algorithms_14',['Alternative Optimization Algorithms',['../index.html#autotoc_md11',1,'']]],
  ['alternative_20likelihood_20calculators_15',['Adding Parameters and Alternative Likelihood Calculators',['../index.html#autotoc_md12',1,'']]],
  ['alternative_20optimization_20algorithms_16',['Alternative Optimization Algorithms',['../index.html#autotoc_md11',1,'']]],
  ['alternative_2ecpp_17',['alternative.cpp',['../alternative_8cpp.html',1,'']]],
  ['analysis_20scripts_18',['Data Analysis Scripts',['../index.html#autotoc_md15',1,'']]],
  ['and_20alternative_20likelihood_20calculators_19',['Adding Parameters and Alternative Likelihood Calculators',['../index.html#autotoc_md12',1,'']]],
  ['arg_20',['Arg',['../bindings_8cpp.html#a5fbc991384a035f0758be9091b13b437',1,'bindings.cpp']]],
  ['authors_21',['Authors',['../index.html#autotoc_md16',1,'']]]
];
