name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install threads
        run: sudo wget -O /usr/include/c++/11/BS_thread_pool.hpp https://raw.githubusercontent.com/bshoshany/thread-pool/master/include/BS_thread_pool.hpp
        
      - name: Create json directory
        run: sudo mkdir /usr/include/c++/11/nlohmann/

      - name: Install JSON
        run: sudo wget -O /usr/include/c++/11/nlohmann/json.hpp https://raw.githubusercontent.com/nlohmann/json/develop/single_include/nlohmann/json.hpp
             
      - name: Install remaining dependencies 
        run: sudo apt-get install -y libboost-math-dev libboost-math1.74-dev


      - name: Install library 
        run: Make install
    #   - name: Login to Docker Hub
    #     uses: docker/login-action@v3
    #     with:
    #       username: ${{ secrets.DOCKERHUB_USERNAME }}
    #       password: ${{ secrets.DOCKERHUB_TOKEN }}

    #   - name: Set up Docker Buildx
    #     uses: docker/setup-buildx-action@v3

    #   - name: Build and push
    #     uses: docker/build-push-action@v5
    #     with:
    #       context: .
    #       file: ./Dockerfile
    #       push: false
    #       tags: ${{ secrets.DOCKERHUB_USERNAME }}/addm.cpp:latest

      - name: Build tests
        run: make test

      - name: Run tests 
        run: bin/addm_test